services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.100.49:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    env_file:
      - /run/secrets/Portfolio/.env
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      management_network:
        ipv4_address: 192.168.100.59

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: portfolio-backend
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.100.49:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    env_file:
      - /run/secrets/Portfolio/.env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      management_network:
        ipv4_address: 192.168.100.60

  db:
    image: postgres:latest
    container_name: portfolio-db
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.100.49:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    ports:
      - "5432:5432"
    env_file:
      - /run/secrets/Portfolio/.env
    volumes:
      - db_data:/var/lib/postgresql
      - ./db/config/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./db/config/02-init-db.sh:/docker-entrypoint-initdb.d/02-init-db.sh:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_ADMIN_USER}" ]
      interval: 5s
      timeout: 60s
      retries: 10
    networks:
      management_network:
        ipv4_address: 192.168.100.61

volumes:
  db_data:

networks:
  management_network:
    external: true
