name: CD - Global Trigger

on:
  workflow_run:
    workflows: ["Backend Tests", "Frontend Tests"]
    types: [completed]
    branches: [main]

jobs:
  trigger-jenkins:
    name: Trigger Jenkins CD
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Notify Jenkins for CD
        run: |
          echo "Triggering Jenkins because ${{ github.event.workflow_run.name }} succeeded."
          curl -X POST "https://jenkins.ega.ovh/generic-webhook-trigger/invoke?token=${{ secrets.JENKINS_TRIGGER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"commit\": \"${{ github.sha }}\", \"ref\": \"${{ github.ref }}\", \"source\": \"${{ github.event.workflow_run.name }}\"}"
